### ISSUE TITLE
Differences between CPU and GPU implementations 

### ISSUE THREAD

**Issue by Catsgomeowmeow** [jagennath-hari/CUDA-Accelerated-Visual-Inertial-Odometry-Fusion#2]
Hey, 
Thanks for providing this great implementation of the UKF. I notice that there are some significant differences between the CPU and GPU implementations. The two main ones that I noticed are that in the CPU implementation, the sigma points are only generated once as opposed to the generation at each iteration for the measurement of sigma points in the GPU node.  The second is the missing Process noise covariance Q in the CPU implementation. 

Just trying to understand the differences between the two implementations.

**Comment by jagennath-hari** [comment]
Hi,

Sorry for the late response, I was developing the CPU to build the framework it is not an exact copy of the GPU version. The idea why I added the CPU version was for others to do some development and testing before implementing their own GPU versions. Think of it as more of an sandbox to play around with.

If I do get time to work on this, I will match both the CPU and GPU implementations.

Regards
